
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jul 11 11:54:34 BRT 2021
//----------------------------------------------------

package AnalisadorSintatico;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int excluir_metodo = 58;
  public static final int criar_op = 21;
  public static final int multiplicidade = 63;
  public static final int atribuicao_classe = 50;
  public static final int atributos_visibilidade = 13;
  public static final int ler_metodo = 56;
  public static final int criar_relacao = 20;
  public static final int letra = 2;
  public static final int final_linha_classe = 9;
  public static final int fecha_colchete = 26;
  public static final int parametros = 11;
  public static final int abre_parenteses = 27;
  public static final int shape = 22;
  public static final int func = 37;
  public static final int se = 60;
  public static final int fecha_parenteses = 28;
  public static final int inicio_funcao = 51;
  public static final int numero = 62;
  public static final int senao = 61;
  public static final int classe = 42;
  public static final int associacoes_atributos = 14;
  public static final int EOF = 0;
  public static final int relationship = 23;
  public static final int enquanto = 41;
  public static final int para = 40;
  public static final int oparitmetico = 4;
  public static final int error = 1;
  public static final int format = 31;
  public static final int relacionamentos_classes = 16;
  public static final int criacao_de_classe = 52;
  public static final int propriedades_operacoes = 15;
  public static final int update = 33;
  public static final int ERROR = 46;
  public static final int variavel = 34;
  public static final int navegabilidade = 19;
  public static final int criar_chaves_fk = 17;
  public static final int delete = 24;
  public static final int relacionamento = 10;
  public static final int opcoes_fk = 18;
  public static final int quebra_linha = 47;
  public static final int virgula = 36;
  public static final int abre_colchete = 25;
  public static final int on_update = 30;
  public static final int atributos_da_classe = 53;
  public static final int define_const = 38;
  public static final int relacional = 3;
  public static final int alterar_metodo = 57;
  public static final int on_delete = 29;
  public static final int number_relationship = 39;
  public static final int comentario = 5;
  public static final int criar_classe = 8;
  public static final int enquanto_for = 43;
  public static final int concurrent = 32;
  public static final int fecha_chave = 45;
  public static final int abre_chave = 44;
  public static final int constante = 35;
  public static final int atribuicao_func = 49;
  public static final int espaco = 48;
  public static final int tipo_atributo = 54;
  public static final int tipos = 6;
  public static final int retorno_metodo = 59;
  public static final int retorno = 12;
  public static final int final_linha = 7;
  public static final int criar_metodo = 55;
}

